---
# Reusable workflow for running Claude Code Action
#
# Required Secrets:
#   CONTEXT7_API_KEY - API key for Context7 MCP server (provides library documentation)
#                      Configure in: Settings → Secrets → Actions → Repository secrets
#
name: Run Claude Code Action
on:
  workflow_call:
    inputs:
      checkout-ref:
        description: Git ref to checkout
        required: false
        type: string
        default: ''
      allowed-bots:
        description: Comma-separated list of allowed bot usernames, or '*' to allow all bots
        required: false
        type: string
        default: ''
      prompt:
        description: Prompt to pass to Claude
        required: true
        type: string
      allowed-tools:
        description: Comma-separated list of allowed tools for Claude
        required: true
        type: string
      claude-args:
        description: Additional arguments to pass to Claude
        required: false
        type: string
        default: ''
      track-progress:
        description: Whether Claude should track progress
        required: false
        type: boolean
        default: true
    secrets:
      claude-oauth-token:
        description: Claude OAuth token
        required: true
      context7-api-key:
        description: API key for Context7 MCP server
        required: false
jobs:
  claude:
    runs-on: ubuntu-latest
    # Note: Permissions are inherited from the calling workflow
    # Each workflow that calls this should define its own permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: 0
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Setup MCP Server
        env:
          CONTEXT7_API_KEY: ${{ secrets.context7-api-key }}
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << EOF
          {
            "mcpServers": {
              "repository-summary": {
                "type": "http",
                "url": "https://agents-md-generator.fastmcp.app/mcp"
              },
              "code-search": {
                "type": "http",
                "url": "https://public-code-search.fastmcp.app/mcp"
              },
              "context7": {
                "type": "http",
                "url": "https://mcp.context7.com/mcp",
                "headers": {
                  "CONTEXT7_API_KEY": "$CONTEXT7_API_KEY"
                }
              }
            }
          }
          EOF
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1.0.23
        with:
          claude_code_oauth_token: ${{ secrets.claude-oauth-token }}
          prompt: ${{ inputs.prompt }}
          track_progress: ${{ inputs.track-progress }}
          allowed_bots: ${{ inputs.allowed-bots }}
          claude_args: |-
            --allowed-tools ${{ inputs.allowed-tools }}
            --mcp-config /tmp/mcp-config/mcp-servers.json
            ${{ inputs.claude-args }}
