---
name: Setup Python Environment
description: Set up Python and install UV package manager with dependencies
inputs:
  setup-xvfb:
    description: Set up Xvfb virtual display server (for E2E tests)
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install UV
      uses: astral-sh/setup-uv@v7
    - name: Install root Python dependencies
      shell: bash
      run: uv sync --group dev
    - name: Install compiler Python dependencies
      shell: bash
      run: make compiler install
    - name: Setup Xvfb
      if: inputs.setup-xvfb == 'true'
      shell: bash
      run: |-
        sudo apt-get update
        sudo apt-get install -y xvfb x11-utils
        Xvfb :99 -screen 0 1024x768x24 > /tmp/xvfb.log 2>&1 &
        XVFB_PID=$!
        export DISPLAY=:99
        echo "DISPLAY=:99" >> "$GITHUB_ENV"

        # Wait for Xvfb to be ready (up to 10 seconds)
        for i in {1..10}; do
          if xdpyinfo -display :99 >/dev/null 2>&1; then
            echo "Xvfb is ready (display :99)"
            break
          fi
          if [ $i -eq 10 ]; then
            echo "Xvfb failed to start after 10 seconds"
            cat /tmp/xvfb.log
            exit 1
          fi
          sleep 1
        done
